# -*- coding: utf-8 -*-
"""Multimodel_rag_agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-DSMllVU_SiVnLP1viICxvJ6tWj1tJcU
"""

!pip install -q langchain
!pip install -q chromadb
!pip install -q sentence-transformers
!pip install -q pymupdf
!pip install -q openai
!pip install -q transformers
!pip install -q pillow
!pip install -q pytesseract
!pip install -q accelerate

from google.colab import files

uploaded = files.upload()

import fitz

def extract_text_from_pdf(pdf_path):

    doc = fitz.open(pdf_path)

    text = ""

    for page in doc:
        text += page.get_text()

    return text

pdf_text = extract_text_from_pdf("/content/sample.pdf")

print(pdf_text[:2000])

from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer(
    'all-MiniLM-L6-v2'
)

embedding = embedding_model.encode(pdf_text)

print(len(embedding))

import chromadb

client = chromadb.Client()

collection = client.create_collection(
    name="rag_collection"
)

collection.add(
    documents=[pdf_text],
    ids=["doc1"]
)

!pip install groq

import os

os.environ["GROQ_API_KEY"] = "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"

from groq import Groq

client = Groq(
    api_key=os.environ.get("GROQ_API_KEY")
)

query = "What topics are discussed in the document?"

context = pdf_text[:3000]

prompt = f"""
You are a helpful AI assistant.

Answer ONLY using the provided context.

Context:
{context}

Question:
{query}
"""

chat_completion = client.chat.completions.create(
    messages=[
        {
            "role": "user",
            "content": prompt,
        }
    ],
    model="llama-3.1-8b-instant",
)

print(chat_completion.choices[0].message.content)

!pip install langchain-text-splitters

from langchain_text_splitters import RecursiveCharacterTextSplitter

text_splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=100
)

chunks = text_splitter.split_text(pdf_text)

print("Number of chunks:", len(chunks))

print(chunks[0])

import chromadb

# The 'client' variable was overwritten by the Groq client.
# To create a new ChromaDB collection, we need to use a ChromaDB client instance.
# Re-instantiate ChromaDB client with a new variable name to avoid conflict.
chroma_client_for_chunks = chromadb.Client()

chunked_rag_collection = chroma_client_for_chunks.create_collection(
    name="chunked_rag"
)

for i, chunk in enumerate(chunks):

    collection.add(
        documents=[chunk],
        ids=[str(i)]
    )

query = "What is deep learning?"

results = collection.query(
    query_texts=[query],
    n_results=2
)

print(results['documents'])

retrieved_chunks = results['documents'][0]

context = "\n".join(retrieved_chunks)

print(context)

prompt = f"""
You are a helpful AI assistant.

Answer ONLY using the context below.

Context:
{context}

Question:
{query}
"""

chat_completion = client.chat.completions.create(
    messages=[
        {
            "role": "user",
            "content": prompt,
        }
    ],
    model="llama-3.1-8b-instant",
)

print(chat_completion.choices[0].message.content)

from google.colab import files

uploaded = files.upload()

!sudo apt install tesseract-ocr

from PIL import Image
import pytesseract

image = Image.open("/content/sample.jpg")

text = pytesseract.image_to_string(image)

print(text)

collection.add(
    documents=[text],
    ids=["image_text_1"]
)

query = "What topics are present in the image?"

results = collection.query(
    query_texts=[query],
    n_results=1
)

print(results['documents'])

retrieved_chunks = results['documents'][0]

context = "\n".join(retrieved_chunks)

print(context)

prompt = f"""
You are a multimodal AI assistant.

Answer ONLY using the provided context.

Context:
{context}

Question:
{query}
"""

chat_completion = client.chat.completions.create(
    messages=[
        {
            "role": "user",
            "content": prompt,
        }
    ],
    model="llama-3.1-8b-instant",
)

print(chat_completion.choices[0].message.content)

!pip install streamlit
!pip install pyngrok

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# from PIL import Image
# import pytesseract
# import fitz
# import chromadb
# from sentence_transformers import SentenceTransformer
# from groq import Groq
# import os
# 
# # -----------------------------
# # GROQ API
# # -----------------------------
# 
# GROQ_API_KEY = "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"
# 
# groq_client = Groq(
#     api_key=GROQ_API_KEY
# )
# 
# # -----------------------------
# # CHROMADB
# # -----------------------------
# 
# chroma_client = chromadb.Client()
# 
# collection = chroma_client.get_or_create_collection(
#     name="multimodal_rag"
# 
# )
# 
# # -----------------------------
# # EMBEDDING MODEL
# # -----------------------------
# 
# embedding_model = SentenceTransformer(
#     'all-MiniLM-L6-v2'
# )
# 
# # -----------------------------
# # STREAMLIT UI
# # -----------------------------
# 
# st.title("Multimodal RAG Agent")
# 
# st.write("Upload PDFs or Images and ask questions.")
# 
# uploaded_file = st.file_uploader(
#     "Upload File",
#     type=["pdf", "jpg", "png", "jpeg"]
# )
# 
# # -----------------------------
# # PDF PROCESSING
# # -----------------------------
# 
# def extract_text_from_pdf(pdf_file):
# 
#     doc = fitz.open(stream=pdf_file.read(), filetype="pdf")
# 
#     text = ""
# 
#     for page in doc:
#         text += page.get_text()
# 
#     return text
# 
# # -----------------------------
# # IMAGE OCR
# # -----------------------------
# 
# def extract_text_from_image(image):
# 
#     text = pytesseract.image_to_string(image)
# 
#     return text
# 
# # -----------------------------
# # FILE INGESTION
# # -----------------------------
# 
# context = ""
# 
# if uploaded_file is not None:
# 
#     file_type = uploaded_file.type
# 
#     if "pdf" in file_type:
# 
#         text = extract_text_from_pdf(uploaded_file)
# 
#         st.success("PDF processed successfully!")
# 
#         context = text
# 
#     else:
# 
#         image = Image.open(uploaded_file)
# 
#         st.image(image)
# 
#         text = extract_text_from_image(image)
# 
#         st.success("Image OCR completed!")
# 
#         context = text
# 
#     collection.add(
#         documents=[context],
#         ids=["doc1"]
#     )
# 
# # -----------------------------
# # QUESTION INPUT
# # -----------------------------
# 
# query = st.text_input(
#     "Ask a question"
# )
# 
# # -----------------------------
# # RAG PIPELINE
# # -----------------------------
# 
# if st.button("Generate Answer"):
# 
#     results = collection.query(
#         query_texts=[query],
#         n_results=1
#     )
# 
#     retrieved_context = results['documents'][0][0]
# 
#     prompt = f'''
#     You are a helpful multimodal AI assistant.
# 
#     Answer ONLY using the context below.
# 
#     Context:
#     {retrieved_context}
# 
#     Question:
#     {query}
#     '''
# 
#     response = groq_client.chat.completions.create(
# 
#         messages=[
#             {
#                 "role": "user",
#                 "content": prompt
#             }
#         ],
# 
#         model="llama-3.1-8b-instant"
#     )
# 
#     answer = response.choices[0].message.content
# 
#     st.subheader("AI Answer")
# 
#     st.write(answer)

!npm install -g localtunnel

!streamlit run app.py &>/content/logs.txt &

!lt --port 8501

!pkill streamlit

!pip install pyngrok

from pyngrok import ngrok

!streamlit run app.py &>/dev/null &

from pyngrok import ngrok

# IMPORTANT: Replace 'YOUR_AUTH_TOKEN' with your actual ngrok authtoken
# You can get your authtoken from https://dashboard.ngrok.com/get-started/your-authtoken after signing up.
# ===> PLEASE REPLACE THIS PLACEHOLDER: "YOUR_AUTH_TOKEN" <===
ngrok.set_auth_token("35E9T7A6tsRgKvZiyrezowZIJ1b_YeHB4kjmdTYjmeB49yuk")

public_url = ngrok.connect(8501)

print(public_url)